- CHANGELOG.md
- lib/index.js
- lib/resolvers/field.js
- lib/resolvers/index.js
- lib/schema/index.js
Allows the GraphQL server framework to be exchanged more easily since the generated GraphQL schema is now fully self-contained. This means it is now also possible to execute queries that contain aliases on the schema directly (without a server) without explicitly providing the `fieldResolver` `ExecutionArgs` property to the `execute` function.
> feat: register alias field resolver in schema generation

- CHANGELOG.md
- package.json
fixes https://github.com/cap-js/cds-adapter-graphql/issues/49
> fix: add `app` folder to `package.json` for publishing to `npm`

- test/schemas/bookshop-graphql.gql
`bookshop-graphql.gql` was previously ignored due to https://github.com/cap-js/graphql/pull/70, but since then https://github.com/cap-js/graphql/pull/73 has changed schema generation. This PR incorporates the new schema generation changes from PR https://github.com/cap-js/graphql/pull/73
(fixes currently failing `bookshop-graphql.gql` test in other PRs)
> test: regenerate `bookshop-graphql` schema

- CHANGELOG.md
- package.json
Requires https://github.com/cap-js/graphql/pull/81 to fix failing test
> chore: prepare next release

- test/resources/types/db/schema.cds
- test/tests/types.test.js
> test: remove decimal precision and scale from types model

- .github/workflows/ci.yml
- package.json
With node 14 it was necessary to keep `cds` in `devDependencies` as well as a `peerDependencies` since node 14 comes with npm 6 and npm<7 does not install `peerDependencies`. Now that node 14 has reached End-of-Life, it has been removed from the matrix tests and the entry from `devDependencies` can be removed. As node 20 is the current node version, it has been added to the matrix tests.
related: https://github.com/cap-js/graphql/commit/6fac2c0372faa888d0a1c2cbcd0eed51242fde7b https://github.com/cap-js/graphql/pull/88
> chore: remove `cds` from `devDependencies` and update node matrix test versions

- CHANGELOG.md
- app/graphiql.html
The dist filename of the GraphiQL Explorer Plugin changed upstream causing the CDN URL to need to be adjusted.
See: https://github.com/graphql/graphiql/releases/tag/%40graphiql%2Fplugin-explorer%400.2.0
> fix: GraphiQL Explorer Plugin CDN URL

- CHANGELOG.md
- app/graphiql.html
The implementation pattern of the GraphiQL Explorer Plugin changed upstream causing the initialization to need to be adjusted.
See: https://github.com/graphql/graphiql/releases/tag/%40graphiql%2Fplugin-explorer%400.3.0
> fix: GraphiQL Explorer Plugin init function usage

- CHANGELOG.md
- lib/logger.js
first merge https://github.com/cap-js/graphql/pull/111
> feat: don't log empty `variables` object

- CHANGELOG.md
- lib/resolvers/error.js
- lib/resolvers/response.js
- test/tests/error-handling-prod.test.js
Previously, all errors were logged as generic errors. This enhancement introduces selective logging of warnings and errors based on their error type. Errors representing client errors (`4xx` range) are now logged as warnings instead of errors.
Additionally, message interpolation has been introduced to resolve error message placeholders into human-readable text.
> feat(logging): enhanced error logging capabilities

- CHANGELOG.md
- test/tests/enrich.test.js
- test/tests/queries/filter.test.js
Re: changelog entry:
```
- Parsing of `null` values in lists
```
&rarr; fixed by https://github.com/cap-js/graphql/pull/139
> test: `null` AST convenience value in lists and filter operator conjunction

- CHANGELOG.md
- lib/compile.js
- test/resources/annotations/srv/protocols.cds
- test/resources/edge-cases/srv/field-named-localized.cds
- test/resources/model-structure/srv/composition-of-aspect.cds
- test/resources/models.json
- test/schemas/annotations.gql
- test/tests/annotations.test.js
When compiling services with `cds.compile.to.graphql` or `.to.gql` (API or CLI), only compile services with GraphQL protocol annotations (such as `@graphql` or `@protocol: 'graphql'`).
> feat: only compile services with GraphQL protocol annotations

- package.json
Prettier dependency is not required, prettier scripts use `npx`.
> chore: Remove prettier dependency

- lib/resolvers/crud/read.js
- package.json
- test/resources/annotations/package.json
- test/resources/bookshop-graphql/package.json
- test/resources/bookshop/package.json
- test/resources/concurrency/package.json
- test/resources/custom-error-formatter/package.json
- test/resources/custom-handlers/package.json
- test/resources/edge-cases/package.json
- test/resources/error-handling/package.json
- test/resources/types/package.json
- test/tests/queries/filter.test.js
- test/tests/queries/paging-offset.test.js
- test/tests/queries/totalCount.test.js
REVISIT:
→ The functions are implemented after OData v4.01 standard which specify them as case sensitive.
→ f74062f it's supported by @cap-js/sqlite
> test: adopt @cap-js/sqlite

- test/tests/types.test.js
This PR also refactors unrelated tests. See this commit for actual relevant change: https://github.com/cap-js/graphql/commit/91615c5c85dd199c896bce7886e634e406411e24 (Results of CDS queries are cast to strings and compared to decimal values that are also cast to strings.)
> test: support decimals returned as strings by CDS query API

- test/tests/error-handling-dev.test.js
- test/tests/error-handling-prod.test.js
Please always follow [our own recommendations for tests](https://pages.github.tools.sap/cap/docs/node.js/cds-test#minimal-assumptions): 
When checking expected errors messages, only check for significant keywords. Don't hardwire the exact error text, as this might change over time, breaking your test unnecessarily.
**DON'T** hardwire on overly specific error messages:
```js
await expect(POST(`/catalog/Books`,...)).to.be.rejectedWith(
'Entity "CatalogService.Books" is readonly'
)
```
**DO** check for the essential information only:
```js
await expect(POST(`/catalog/Books`,...)).to.be.rejectedWith(
/readonly/i
)
```
> Fixing assert tests

- lib/resolvers/parse/ast2cqn/where.js
Fixes: Revisit 1 = 1 checks in our codebase. hdb does not support that. Switch to '1' = '1'.
> Fix static checks

- CHANGELOG.md
- lib/compile.js
- package.json
- test/resources/annotations/srv/protocols.cds
- test/schemas/annotations.gql
- test/tests/annotations.test.js
Use `serviceinfo` to determine services to compile instead of directly inspecting service definition for `@protocol` or `@graphql` annotations, since this logic is duplicated in `@sap/cds`.
> feat: use `serviceinfo` to determine services to compile

- test/tests/graphiql.test.js
- test/tests/localized.test.js
- test/tests/mutations/create.test.js
- test/tests/mutations/delete.test.js
- test/tests/mutations/update.test.js
- test/tests/queries/aliases.test.js
- test/tests/queries/filter.test.js
- test/tests/queries/fragments.test.js
- test/tests/queries/meta.test.js
- test/tests/queries/orderBy.test.js
- test/tests/queries/paging-offset.test.js
- test/tests/queries/queries.test.js
- test/tests/queries/totalCount.test.js
- test/tests/queries/variables.test.js
alternatively, we can remove the requires annotation in the local bookshop sample in the tests
> fix: test require auth, admin service is protected

- test/resources/concurrency/srv/concurrency.js
- test/resources/concurrency/srv/data-and-errors.js
Refactoring to use `require('node:timers/promises').setTimeout` rather than `require('util').promisify(setTimeout)`.
No need to promisify a function as there's a native promise version of that: [Timers Promises API](https://nodejs.org/api/timers.html#timerspromisessettimeoutdelay-value-options)
> refactor: Use node:timers/promises/setTimeout

- CHANGELOG.md
- package.json
closes https://github.com/cap-js/graphql/issues/203
> chore: prep next release

- lib/resolvers/error.js
Using such mocked `req` objects is pretty bad practice, as it makes assumptions about internal implementations not using any of the public API features from Node.js and express. → please merge and publish that asap to unblock us for upcoming releases of `@sap/cds`
> fix: Mocked req objects should support req.get(header)

- CHANGELOG.md
- lib/GraphQLAdapter.js
- lib/logger.js
- test/tests/error-handling-dev.test.js
- test/tests/error-handling-prod.test.js
- test/tests/logger-dev.test.js
- test/tests/logger-prod.test.js
Example query:
```gql
query MyQuery {
AdminService {
Books(filter: {title: {contains: ") foo"}}) {
nodes {
ID
}
}
}
}
```
Previous log output (in production):
```gql
[graphql] - POST { operationName: 'MyQuery' } 
query MyQuery {
AdminService {
Books( *** ) foo"}}) {
nodes {
ID
}
}
}
}
```
New log output (in production):
```gql
[graphql] - POST { operationName: 'MyQuery' } 
query MyQuery {
AdminService {
Books(filter: "***") {
nodes {
ID
}
}
}
}
```
> fix(logging): sanitization if literal values contain parentheses
